name: wps-office-all-lang-no-internet
version: '10.1.0.6757'
summary:  WPS Office Suite all languages with no internet connection
description: |
   ABOUT WPS OFFICE
   WPS Office, is an office productivity suite. WPS Office including Writer, Presentation and Spreadsheets, is a powerful office suite, which is able to process word file, produce wonderful slides, and analyze data as well. It is deeply compatible with all of the latest Microsoft Office file formats. It can easily open and read the documents created with Microsoft Office. This is the Linux version, and it's now a TESTING package. Website: http://wps-community.org
   
   ABOUT THIS PACKAGE
   WPS-office snap package is shipped by default only with English and Chinese. Due to the non modifiable aspect of snap packages, it is currently impossible to install other languages and spellchecker.    
   This package have been built with English (GB, US), French (FR), Indonesian (ID), Portuguese (BR, PT), Russian (RU) and Chinese (CN) interface, and English (AU, GB, US), Spanish (ES, MX), French (FR), Dutch (NL), Polish (PL), Portuguese (BR, PT) and Russian (RU) dictionnaries.
   Moreover Because I'm security freak and I don't trust china's privacy policy, I made this package without internet plug, which means that this version of WPS in unable to connect to the internet. I made this in order to keep your computer backdoor free and your data private.
   The files used to create this packages are available at https://github.com/cyrpaut/wps-office-ann-lang-no-internet. Please feel free to help me upgrading this package. 

architectures:
- amd64
confinement: strict
grade: stable

parts:
  wps-office-all-lang-no-internet:
    source: ./wps-office-bin/
    plugin: dump    

apps:
  et:
    command: usr/bin/et
    desktop: gui/et.desktop
    plugs:
    - alsa
    - cups-control
    - desktop
    - home
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11
  wpp:
    command: usr/bin/wpp
    desktop: gui/wpp.desktop
    plugs:
    - alsa
    - cups-control
    - desktop
    - home
    - opengl
    - pulseaudio
    - removable-media
    - wayland
    - x11
  wps:
    command: usr/bin/wps
    desktop: gui/wps.desktop
    plugs:
    - gsettings
    - home
    - pulseaudio
    - unity7
    - x11
    - opengl
    - cups-control
    - alsa
    - desktop
